@startuml
'https://plantuml.com/class-diagram

package "Stock Trader UI" as p1 #FFFFBA {}
package "GUI Lib" as p2 #FFFFBA {}
package "Portfolio UI" as p3 #FFFFBA {}

p1 .right.> p2
note on link #FCA985
    **dependencies**
    --
    In dit voorbeeld staat weergegeven hoe
    een dependency eruit ziet tussen packages.
end note
p2 <.left. p3

note right of p3 #FCA985
    **package**
    --
    Een package geeft een namespace weer van
    een bepaald onderdeel van de applicatie.
    Alles wat in een package zit valt onder de
    namespace van die specifieke package.

    het is ook handig om de daadwerkelijke
    code in de directory structuur te verwerken
    op de manier dat de packages uitgewerkt staan.
end note

@enduml