@startuml
'https://plantuml.com/class-diagram

left to right direction

note as n1 #FCA985
    **layered_example**
    In dit voorbeeld heb ik een meer uitgebreidere variant
    van een nested package systeem uitgewerkt.

    Omdat het positioneren van de verschillende packages
    erg lastig gaat met plantuml heb ik er voor gekozen
    om alle packages zonder inhoud weer te geven in de package
    **"layered_example"**. Naast de "layered_example" staan
    de packages die inhoudelijk iets bevatten nogmaals weergegevn
    met het stereotype **<<expanded>>**.
    Met het gebruik van verschillende kleuren heb ik een poging
    gedaan om er een overzichtelijk diagram van te maken.
end note

package layered_example as pkg0 #FFFFBA{
    package "user" as pkg1 #DDDDDD {}
    package "<<collapsed>>\npresentation_layer" as pkg2 #FFB3BA{}
    package "<<collapsed>>\nservices_layer" as pkg3 #FFDFBA{}
    package "external_systems" as pkg4 #DDDDDD {}

    package "<<collapsed>>\nbusiness_layer" as pkg5 #BAFFC9{}
    package "<<collapsed>>\ndata_layer" as pkg6 #BAE1FF{}
    package "<<collapsed>>\ncross_cutting" as pkg7 #CBAACB{}
    package "data_sources" as pkg8 #DDDDDD {}
    package "external_services" as pkg9 #DDDDDD {}

    pkg3 .[hidden]left.> pkg2

    pkg1 ..> pkg2
    pkg4 ..> pkg3

    pkg3 .down.> pkg5
    pkg2 .down.> pkg5

    pkg5 -[hidden]down-> pkg6

    pkg5 .down.> pkg6
    pkg6 ..> pkg8
    pkg6 ..> pkg9

    pkg7 <.. pkg2
    pkg7 <.. pkg3
    pkg7 <.. pkg5
    pkg7 <.. pkg6
}

@enduml