@startuml
'https://plantuml.com/class-diagram

package "package A" as p1 #FFFFBA {}
package "package B" as p2 #FFFFBA {}

p1 .right.> p2 : <<import>>

package "package A" as p3 #FFFFBA {}
package "package B" as p4 #FFFFBA {}

p3 .right.> p4 : <<access>>

p1 -[hidden]down-> p2
p2 -[hidden]down-> p4

note right of p2 #FCA985
    **<<import>>**
    --
    Dit stereotype geeft aan dat packageA
    packageB importeerd.
end note

note right of p4 #FCA985
    **<<access>>**
    --
    Dit stereotype geeft aan dat packageC
    packageD gebruikt.

    Als je dit stereotype gebruikt geef dan
    ook nog hoe de ge-'access'-te package
    gebruikt wordt.
end note

@enduml