@startuml
'https://plantuml.com/state-diagram

state s1 as "simple state"{
    s1 : **entry** / doe iets eenmalig
    s1 : **do** / doe iets continue
    s1 : doe iets dadelijk / **defer**
    s1 : **exit** / doe iets eenmalig
}


[*] --> s1
note on link
    **initial state**
    statemachine begint altijd hier.
    Een statemachine heeft altijd mini-
    maal een initial node.
end note
s1 --> [*]
note on link
    **Final state**
    bij de final node zal de statemachine
    op een 'nette' manier afgesloten worden.
    Het is niet noodzakelijk voor een
    statemachine om een final node te
    bevatten.
end note

@enduml