@startuml
'https://plantuml.com/state-diagram

state state_2 as "**transition**" {
    state state_0 as "**source state**" {
        state_0 : **[1]** **entry** / do action
        state_0 : **[2]** **do** / do activity
        state_0 : **[7]** **defer** / do action later
        state_0 : **[5]** **exit** / do action
    }
    state state_1 as "**target state**" {
        state_1 : **[8]** **entry** / do action
        state_1 : **[-]** **do** / do activity
        state_1 : **[-]** **defer** / do action later
        state_1 : **[-]** **exit** / do action
    }
    state_0 --> state_1 : **[3]** trigger(parameter-list) \n **[4]** [guard] **[6]** /actions
}

note as n1 #FCA985
    **transitie volgorde**
    --
    De verschillende elementen van states en
    transitie worden op een bepaalde volgorde
    uitgevoerd, deze volgorde is links weer-
    gegeven door middel van **[x]** markeringen.

    --
    **1.** De entry action van de source state.
    **2.** De do activity van de source state.
    **3.** De trigger van de transitie.
    **4.** De guard checkt de waarde.
    **5.** De exit action van de source state.
    **6.** De actions van de transitie.
    **7.** De eventuele defers.
    **8.** De entry van de target state.

end note

@enduml