@startuml
'https://plantuml.com/state-diagram


state state_0 as "**source state**"
state state_1 as "**target state**"
state_0 --> state_1 : \t**trigger(parameter list)[guard]/action**


note as n1 #FCA985
   **1.** De **trigger** en **(parameters)**
   --
   Een trigger wordt aangeroepen door een
   evenement, in de parameter-list kan er
   vervolgens weergegeven worden wat er
   precies fout is gegaan. Een voorbeeld
   van een trigger is het volgende:

   **""alarm(tooHot: alarmType)""**

   --
   **2.** De **[guard]**
   --
   Een transitie kan ook een guard bevatten
   een guard checkt een bepaalde waarde en
   retourneerd een boolean, als de waarde
   voldoet aan de guard zal er **""true""**
   geretourneerd worden, anders **""false""**, duh.

   --
   **3.** nul of meer **/actions**
   --
   Als een transitie uitgevoerd is zullen de
   acties van een transitie uitgevoerd worden.
end note




'n1 -[hidden]left-> state_0
'n3 -[hidden]left-> state_1

'n1 -[hidden]up> n2
'n2 -[hidden]> n3

'additional hidden arrows remove the
'arrows all together.
'n1 -[hidden]down> n2
'n2 -[hidden]down> n3



'n1 -[hidden]-> state_0
'n1 -[hidden]-> state_1

'scale 350 width
'[*] --> NotShooting
'
'state NotShooting {
'  [*] --> Idle
'  Idle --> Configuring : EvConfig
'  Configuring --> Idle : EvConfig
'}
'
'state Configuring {
'  [*] --> NewValueSelection
'  NewValueSelection --> NewValuePreview : EvNewValue
'  NewValuePreview --> NewValueSelection : EvNewValueRejected
'  NewValuePreview --> NewValueSelection : EvNewValueSaved
'
'  state NewValuePreview {
'     State1 -> State2
'  }
'
'}
@enduml