@startuml
'https://plantuml.com/use-case-diagram

actor actor1 as "user"
rectangle rect1 as "system boundary" #DDDDDD{
    usecase usecase1 as "//<<CRUD>>//\n**maintain**"  #CBAACB
}
actor1 -right- usecase1

rectangle rect2 as "**<<CRUD>>**" #DDDDDD{
    usecase usecase2 as "create" #BAFFC9
    usecase usecase3 as "read" #BAFFC9
    usecase usecase4 as "update" #BAFFC9
    usecase usecase5 as "delete" #BAFFC9
}

usecase1 <.. usecase2 : **<<include>>**
usecase1 <.. usecase3 : **<<include>>**
usecase1 <.. usecase4 : **<<include>>**
usecase1 <.. usecase5 : **<<include>>**

note as n1 #FCA985
    **user defined stereotype**
    --
    In dit voorbeeld is het gebruik en de uitwerking van
    een **user defined stereotype (UDS)** weergegeven.

    Een UDS houdt in dat het een samenvatting is van
    veel voorkomende use case combinaties die altijd in
    dezelfde vorm voorkomen.
    CRUD komt veel voor bij dingen zoals databases,
    het aanmaken, bekijken, veranderen en verwijderen
    van onderdelen.

    --
    **<<CRUD>>**
    --
    Het UDS uit dit voorbeeld is <<CRUD>>, CRUD staat
    voor create, read, update en delete.
end note

@enduml