@startuml
'https://plantuml.com/use-case-diagram

usecase usecase1 as "place_order" #BAFFC9
usecase usecase2 as "cancel_order" #BAFFC9
usecase usecase3 as "change_order" #BAFFC9
usecase usecase4 as "add_to_cart\n--\n**extension point**\nuser_login" #FFB3BA
usecase usecase5 as "login"

usecase5 <.. usecase1 : **<<include>>**
usecase5 <.. usecase2 : **<<include>>**
usecase5 <.. usecase3 : **<<include>>**
usecase5 ..> usecase4 : **<<extend>>**
note right on link #FFB3BA
    **condition** user opens personal cart
    **extension point** login required
end note

usecase1 -[hidden]down-> usecase5
usecase2 -[hidden]down-> usecase5
usecase3 -[hidden]down-> usecase5
usecase4 -[hidden]right-> usecase5


note as n1 #FCA985
    **extend**
    --
    Het **<<extend>>** stereotype geeft een
    alternative route weer.
    Als deze use case uitgevoerd wordt
    is het mogelijk dat de andere
    ook uitgevoerd zal worden maar niet
    noodzakelijk.

    --
    **extension point**
    --
    Een **"extension point"** kan worden
    gebruikt voor een meer gedetaileerde
    uitleg van de procedure op een andere
    locatie om de overzichtelijkheid te
    behouden.
end note

@enduml