@startuml
'https://plantuml.com/use-case-diagram

rectangle r1 as "<<include>>"{
    usecase r1_uc1 as "place_order"
    usecase r1_uc2 as "cancel_order"
    usecase r1_uc3 as "change_order"
    usecase r1_uc4 as "add_to_cart
    --
    **extension point**
    user_login"
    usecase r1_uc5 as "login"

    r1_uc5 <.. r1_uc1 : **<<include>>**
    r1_uc5 <.. r1_uc2 : **<<include>>**
    r1_uc5 <.. r1_uc3 : **<<include>>**
    r1_uc5 ..> r1_uc4 : <<extend>>

    r1_uc1 -[hidden]down-> r1_uc5
    r1_uc2 -[hidden]down-> r1_uc5
    r1_uc3 -[hidden]down-> r1_uc5
    r1_uc4 -[hidden]right-> r1_uc5
}
note as n1
    Het **<<include>>** stereotype betekend dat
    een bepaalde use usecase niet uitgevoerd
    kan worden zonder het ge-include onderdeel
    ook uit te voeren.

    In dit voorbeeld staat weergegeve dat een
    gebruiker geen order kan plaatsen zonder eerst
    in te loggen.
    Verder kan een order niet meer geannuleerd
    of veranderd worden als de gebruiker niet
    ingelogd is.
end note

@enduml