@startuml
'https://plantuml.com/use-case-diagram

usecase usecase1 as "place_order" #BAFFC9
usecase usecase2 as "cancel_order" #BAFFC9
usecase usecase3 as "change_order" #BAFFC9
usecase usecase4 as "add_to_cart\n--\n**extension point**\nuser_login" #FFB3BA
usecase usecase5 as "login"

usecase5 <.. usecase1 : **<<include>>**
usecase5 <.. usecase2 : **<<include>>**
usecase5 <.. usecase3 : **<<include>>**
usecase5 ..> usecase4 : **<<extend>>**
note right on link #FFB3BA
    **condition** user opens personal cart
    **extension point** login required
end note

usecase1 -[hidden]down-> usecase5
usecase2 -[hidden]down-> usecase5
usecase3 -[hidden]down-> usecase5
usecase4 -[hidden]right-> usecase5

note as n1 #FCA985
    **include**
    --
    Het **<<include>>** stereotype betekend dat
    een bepaalde use usecase niet uitgevoerd
    kan worden zonder het ge-include onderdeel
    ook uit te voeren.

    In dit voorbeeld staat weergegeve dat een
    gebruiker geen order kan plaatsen zonder eerst
    in te loggen.
    Verder kan een order niet meer geannuleerd
    of veranderd worden als de gebruiker niet
    ingelogd is.
end note

@enduml